services:
  api-pixel-coffee:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./.env:/var/www/html/.env
      - ./public:/var/www/html/public
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: api_pixel_coffee_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
  db:
    image: mariadb:11
    container_name: api_pixel_coffee_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: api_pixel_coffee
      MARIADB_USER: api_pixel_coffee_user
      MARIADB_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./bdd_pixel_coffee.sql:/docker-entrypoint-initdb.d/bdd_pixel_coffee.sql
volumes:
  db_data: